name: tax_mock_app
description: 假个人所得税APP

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
